config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Deviseのマッピングはするが、skipして何も設定しない
  devise_for :users, skip: %i[sessions registrations],
                     controllers: {
                       confirmations: 'users/confirmations',
                       omniauth_callbacks: 'users/omniauth_callbacks',
                       passwords: 'users/passwords'
                     }
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    post 'guest_login', to: 'users/sessions#guest_login', as: :guest_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'users/registrations#new', as: :new_user_registration
    post 'signup', to: 'users/registrations#create', as: :user_registration
    get 'account/edit', to: 'users/registrations#edit', as: :edit_account
    put 'account', to: 'users/registrations#update', as: :account
    delete 'account', to: 'users/registrations#destroy', as: :destroy_account
  end
  root 'static_pages#top'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :feedbacks, only: %i[new create]
  resources :crops do
    collection do
      get :search
    end
  end
  resources :users, only: %i[show]
  namespace :mypage do
    get 'following', to: 'relationships#following'
    get 'follower', to: 'relationships#follower'
    resources :notifications, only: %i[index]
  end
  resources :reservations, only: %i[index new create destroy]
  resources :bookmarks, only: %i[index create destroy]
  resources :relationships, only: %i[create destroy]
  resources :chatrooms, only: %i[index create show], shallow: true do
    resources :chats
  end
  resources :notifications, only: [] do
    patch :read, on: :member
    patch :read_all, on: :collection
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/shared/_before_login_header.html.slim
.navbar-toolbar
  .my-sm-0.text-center.flex-column
    .d-inline-flex.align-items-center.text-nowrap.fs-sm
      .navbar-toolbar
        - unless current_page?(new_user_session_path)
          = link_to 'ログイン', new_user_session_path, class: 'btn btn-primary btn-sm rounded-pill navbar-tool ms-1 ms-lg-0 me-lg-2'
      .navbar-toolbar
        - unless current_page?(new_user_registration_path)
          = link_to 'アカウント登録', new_user_registration_path, class: 'btn btn-outline-primary btn-sm rounded-pill navbar-tool ms-1 ms-lg-0 me-lg-2'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_footer.html.slim
footer.bg-accent.pt-2.sort id="bottom"
  .my-sm-0.text-center.pt-1.flex-column
    .d-inline-flex.align-items-center.text-nowrap.fs-sm
      .ps-sm-2.text-muted
        span.fw-medium.text-light.me-1
          = link_to '使い方', about_path
      .ps-sm-1.ps-1.border-start.border-light
        span.fw-medium.text-light.me-1
          = link_to '利用規約', terms_path
      .ps-sm-1.ps-1.border-start.border-light
        span.fw-medium.text-light.me-1
          = link_to 'プライバシーポリシー', privacy_path
      .ps-sm-1.ps-1.border-start.border-light
        span.fw-medium.text-light.me-1
          = link_to 'お問い合わせ', new_feedback_path
  .pb-4.fs-xs.text-center.text-md-center.text-white
    | © LocalCrops. All rights reserved.

app/views/shared/_google_analytics.html.slim
script async="" src="https://www.googletagmanager.com/gtag/js?id=G-39E58NFJ90"
javascript:
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());
    gtag("config", "G-39E58NFJ90");
    if (#{raw current_user.to_json}) {
        gtag('set', {'user_id': #{raw current_user.to_json}.id});
    }

app/views/shared/_header.html.slim
.navbar-toolbar.d-flex.align-items-center.order-lg-3
  button.navbar-toggler data-bs-target="#navbarOffcanvas" data-bs-toggle="offcanvas" type="button"
    span.btn.btn-outline-dark.rounded-pill.btn-sm メニュー
#navbarOffcanvas.offcanvas.offcanvas-end.me-auto.order-lg-2
  .offcanvas-header
    h5.offcanvas-title メニュー
    button.btn-close.text-reset aria-label="Close" data-bs-dismiss="offcanvas" type="button"
  .offcanvas-body
    ul.navbar-nav
      li.nav-item
        = link_to user_path(current_user), class: "nav-link" do
          i.ci-user.me-1
          | プロフィール
      li.nav-item
        = link_to about_path, class: "nav-link" do
          i.ci-document.me-1
          | 使い方
      li.nav-item
        = link_to crops_path, class: "nav-link" do
          i.ci-view-grid.me-1
          | 作物一覧
      li.nav-item
        = link_to new_crop_path, class: "nav-link" do
          i.ci-carrot.me-1
          | 作物登録
      li.nav-item
        = link_to reservations_path, class: "nav-link" do
          i.ci-view-list.me-1
          | 予約リスト
      li.nav-item
        = link_to bookmarks_path, class: "nav-link" do
          i.ci-bookmark.me-1
          | ブックマーク
      li.nav-item.dropdown
        a.nav-link.dropdown-toggle data-bs-auto-close="outside" data-bs-toggle="dropdown"
          i.ci-add-user.me-1
          | ユーザー
        ul.dropdown-menu
          li
            = link_to 'フォロー', mypage_following_path, class: "dropdown-item"
          li
            = link_to 'フォロワー', mypage_follower_path, class: "dropdown-item"
      li.nav-item
        = link_to chatrooms_path, class: "nav-link" do
          i.ci-chat.me-1
          | チャットルーム
      li.nav-item
        = link_to mypage_notifications_path, class: "nav-link d-flex align-items-center" do
          i.ci-bell.me-1
          | 通知
          = render 'shared/unread_badge'
      li.nav-item
        = link_to destroy_user_session_path, class: "nav-link logout-button", method: :delete, data: { confirm: 'ログアウトします。よろしいですか?' } do
          i.ci-sign-out.me-1
          | ログアウト
      li.nav-item
        = render 'shared/search_form'

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_search_form.html.slim
= search_form_for @q, url: search_crops_path do |f|
  .input-group
    i.ci-search.position-absolute.top-50.translate-middle-y.text-muted.fs-base.ms-3
    = f.search_field :name_or_description_cont, placeholder: "作物名、説明で検索", class: 'form-control'
    = f.submit nil, class: 'btn btn-primary'

app/views/shared/_unread_badge.html.slim
- if current_user.notifications.unread.count > 0
  span.badge.rounded-pill.bg-danger.ms-2
    = current_user.notifications.unread.count