config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Deviseのマッピングはするが、skipして何も設定しない
  devise_for :users, skip: %i[sessions registrations],
                     controllers: {
                       confirmations: 'users/confirmations',
                       omniauth_callbacks: 'users/omniauth_callbacks',
                       passwords: 'users/passwords'
                     }
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    post 'guest_login', to: 'users/sessions#guest_login', as: :guest_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'users/registrations#new', as: :new_user_registration
    post 'signup', to: 'users/registrations#create', as: :user_registration
    get 'account/edit', to: 'users/registrations#edit', as: :edit_account
    put 'account', to: 'users/registrations#update', as: :account
    delete 'account', to: 'users/registrations#destroy', as: :destroy_account
  end
  root 'static_pages#top'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :feedbacks, only: %i[new create]
  resources :crops do
    collection do
      get :search
    end
  end
  resources :users, only: %i[show]
  namespace :mypage do
    get 'following', to: 'relationships#following'
    get 'follower', to: 'relationships#follower'
    resources :notifications, only: %i[index]
  end
  resources :reservations, only: %i[index new create destroy]
  resources :bookmarks, only: %i[index create destroy]
  resources :relationships, only: %i[create destroy]
  resources :chatrooms, only: %i[index create show], shallow: true do
    resources :chats
  end
  resources :notifications, only: [] do
    patch :read, on: :member
    patch :read_all, on: :collection
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id                :bigint           not null, primary key
#  notification_type :integer          not null
#  read              :boolean          default("unread"), not null
#  subject_type      :string(255)      not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  subject_id        :bigint           not null
#  user_id           :bigint           not null
#
# Indexes
#
#  index_notifications_on_subject  (subject_type,subject_id)
#  index_notifications_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Notification < ApplicationRecord
  include Rails.application.routes.url_helpers
  belongs_to :user
  belongs_to :subject, polymorphic: true
  enum notification_type: { reserved_to_own_crop: 0,
                            bookmarked_to_own_crop: 1,
                            followed_me: 2,
                            chat_to_me: 3,
                            create_crop_by_follow_user: 4 }
  enum read: { unread: false, read: true }

  def redirect_path
    case notification_type.to_sym
    when :reserved_to_own_crop
      reservations_path
    when :bookmarked_to_own_crop
      crop_path(subject.crop)
    when :followed_me
      user_path(subject.follower)
    when :chat_to_me
      chatroom_path(subject.chatroom)
    when :create_crop_by_follow_user
      crop_path(subject)
    end
  end
end

app/controllers/mypage/base_controller.rb
class Mypage::BaseController < ApplicationController
end

app/controllers/mypage/notifications_controller.rb
class Mypage::NotificationsController < Mypage::BaseController
  def index
    @notifications = current_user.notifications.order(created_at: :desc).page(params[:page]).per(12)
  end
end

app/controllers/mypage/relationships_controller.rb
class Mypage::RelationshipsController < Mypage::BaseController
  def following
    @users = current_user.following.page(params[:page]).per(12)
  end

  def follower
    @users = current_user.followers.page(params[:page]).per(12)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def read
    notification = current_user.notifications.find(params[:id])
    notification.read! if notification.unread?
    redirect_to notification.redirect_path
  end

  def read_all
    notifications = current_user.notifications.where(read: 'unread')
    notifications.each(&:read!)
    redirect_to mypage_notifications_path, success: 'すべて既読にしました'
  end
end

app/views/mypage/notifications/_bookmarked_to_own_crop.html.slim
.align-items-start class="border-bottom #{'read' if notification.read?}"
  = link_to read_notification_path(notification), class: "notification-item", method: :patch do
    = image_tag notification.subject.user.avatar, class: 'rounded-circle me-1', size: '30x30'
    object
      = link_to notification.subject.user.username, user_path(notification.subject.user)
      | さんがあなたの
    object
      = link_to '作物', crop_path(notification.subject.crop)
      | をブックマークしました。
      = l notification.created_at, format: :short

app/views/mypage/notifications/_chat_to_me.html.slim
.align-items-start class="border-bottom #{'read' if notification.read?}"
  = link_to read_notification_path(notification), class: "notification-item", method: :patch do
    = image_tag notification.subject.user.avatar, class: 'rounded-circle me-1', size: '30x30'
    object
      = link_to notification.subject.user.username, user_path(notification.subject.user)
      | さんが
    object
      = link_to 'チャットルーム', chatroom_path(notification.subject.chatroom)
      | にコメントしました。
      = l notification.created_at, format: :short

app/views/mypage/notifications/_create_crop_by_follow_user.html.slim
.align-items-start class="border-bottom #{'read' if notification.read?}"
  = link_to read_notification_path(notification), class: "notification-item", method: :patch do
    = image_tag notification.subject.user.avatar, class: 'rounded-circle me-1', size: '30x30'
    object
      = link_to notification.subject.user.username.truncate(15), user_path(notification.subject.user)
      | さんが
    object
      = link_to '作物', crop_path(notification.subject)
      | を登録しました。
      = l notification.created_at, format: :short

app/views/mypage/notifications/_followed_me.html.slim
.align-items-start class="border-bottom #{'read' if notification.read?}"
  = link_to read_notification_path(notification), class: "notification-item", method: :patch do
    = image_tag notification.subject.follower.avatar, class: 'rounded-circle me-1', size: '30x30'
    object
      = link_to notification.subject.follower.username, user_path(notification.subject.follower)
      | さんがあなたをフォローしました。
      = l notification.created_at, format: :short

app/views/mypage/notifications/_reserved_to_own_crop.html.slim
.align-items-start class="border-bottom #{'read' if notification.read?}"
  = link_to read_notification_path(notification), class: "notification-item", method: :patch do
    = image_tag notification.subject.user.avatar, class: 'rounded-circle me-1', size: '30x30'
    object
      = link_to notification.subject.user.username.truncate(15), user_path(notification.subject.user)
      | さんがあなたの
    object
      = link_to '作物', crop_path(notification.subject.crop)
      | を予約しました。
      = l notification.created_at, format: :short

app/views/mypage/notifications/_unread_badge.html.slim
- if current_user.notifications.unread.count > 0
  span.badge.badge-danger.navbar-badge.position-absolute style='top: 0; right: 0'
    = current_user.notifications.unread.count

app/views/mypage/notifications/index.html.slim
- set_meta_tags title: '通知一覧ページ'
.page-title-overlap.bg-accent.pt-4.pb-5
  .container.pt-2.pb-3.pt-lg-3.pb-lg-4
    .d-flex.justify-content-between.pb-3
      .order-lg-1.pe-lg-4.text-left.text-lg-start
        h1.h3.text-light.mb-2.ms-5 通知
      .order-lg-1.pe-lg-4.text-end
        = link_to 'すべて既読にする', read_all_notifications_path, class: 'btn btn-secondary  btn-sm rounded-pill', method: :patch
.container.pb-3
  .bg-light.shadow-lg.rounded-3.overflow-hidden.p-2
    .row
      .col-md-10.offset-md-1
      - if @notifications.present?
        - @notifications.each do |notification|
          = render "#{notification.notification_type}", notification: notification
      - else
        .text-center.font-weight-bold
          | お知らせはありません
      = paginate @notifications, theme: 'bootstrap-5'