config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Deviseのマッピングはするが、skipして何も設定しない
  devise_for :users, skip: %i[sessions registrations],
                     controllers: {
                       confirmations: 'users/confirmations',
                       omniauth_callbacks: 'users/omniauth_callbacks',
                       passwords: 'users/passwords'
                     }
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    post 'guest_login', to: 'users/sessions#guest_login', as: :guest_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'users/registrations#new', as: :new_user_registration
    post 'signup', to: 'users/registrations#create', as: :user_registration
    get 'account/edit', to: 'users/registrations#edit', as: :edit_account
    put 'account', to: 'users/registrations#update', as: :account
    delete 'account', to: 'users/registrations#destroy', as: :destroy_account
  end
  root 'static_pages#top'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :feedbacks, only: %i[new create]
  resources :crops do
    collection do
      get :search
    end
  end
  resources :users, only: %i[show]
  namespace :mypage do
    get 'following', to: 'relationships#following'
    get 'follower', to: 'relationships#follower'
    resources :notifications, only: %i[index]
  end
  resources :reservations, only: %i[index new create destroy]
  resources :bookmarks, only: %i[index create destroy]
  resources :relationships, only: %i[create destroy]
  resources :chatrooms, only: %i[index create show], shallow: true do
    resources :chats
  end
  resources :notifications, only: [] do
    patch :read, on: :member
    patch :read_all, on: :collection
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id          :bigint           not null, primary key
#  body        :text(65535)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  chatroom_id :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_chats_on_chatroom_id  (chatroom_id)
#  index_chats_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (chatroom_id => chatrooms.id)
#  fk_rails_...  (user_id => users.id)
#
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
  has_one :notification, as: :subject, dependent: :destroy
  validates :body, presence: true, length: { maximum: 1000 }
  scope :recent, ->(count) { order(created_at: :desc).limit(count) }
  after_create_commit :create_notifications

  private

  def create_notifications
    Notification.create(user: user.partner(chatroom), subject: self, notification_type: :chat_to_me)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chatroom = Chatroom.find(params[:chatroom_id])
    @reservations = Reservation.includes(user: { avatar_attachment: :blob }, crop: { picture_attachment: :blob })
                               .where(user_id: current_user.id, crop_id: current_user.partner(@chatroom).crops.ids)
                               .or(Reservation.where(user_id: current_user.partner(@chatroom).id, crop_id: current_user.crops.ids))
                               .recent(3)
  end

  def create
    @chat = current_user.chats.build(chat_params)
    if @chat.save
      ActionCable.server.broadcast(
        "chatroom_#{@chat.chatroom_id}",
        { type: :create, html: (render_to_string partial: 'chat', locals: { chat: @chat }, layout: false), chat: @chat.as_json }
      )
      head :ok
    else
      head :bad_request
    end
  end

  def edit
    @chat = current_user.chats.find(params[:id])
  end

  def update
    @chat = current_user.chats.find(params[:id])
    if @chat.update(chat_update_params)
      ActionCable.server.broadcast(
        "chatroom_#{@chat.chatroom_id}",
        { type: :update, html: (render_to_string partial: 'chat', locals: { chat: @chat }, layout: false), chat: @chat.as_json }
      )
      head :ok
    else
      head :bad_request
    end
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @chat.destroy!
    ActionCable.server.broadcast(
      "chatroom_#{@chat.chatroom_id}",
      { type: :delete, html: (render_to_string partial: 'chat', locals: { chat: @chat }, layout: false), chat: @chat.as_json }
    )
    head :ok
  end

  private

  def chat_params
    params.require(:chat).permit(:body).merge(chatroom_id: params[:chatroom_id])
  end

  def chat_update_params
    params.require(:chat).permit(:body)
  end
end

app/views/chats/_chat.html.slim
- if current_user&.own?(chat)
  li.media.mb-3.p-2 id="chat-#{chat.id}" data-sender-id="#{chat.user.id}"
    .media-body.my-comment
      = simple_format(chat.body)
    div.text-right.d-inline-flex.crud-area
      = link_to chat_path(chat), class: 'me-2 delete-button', method: :delete, data: { confirm: '本当に削除しますか？' }, remote: true do
        i.fa-solid.fa-trash
      = link_to edit_chat_path(chat), class: 'me-3 edit-button', remote: true do
        i.fa-solid.fa-pen-to-square
      div.text-right
        = chat.decorate.created_at
- else
  li.media.mb-3.p-2 id="chat-#{chat.id}" data-sender-id="#{chat.user.id}"
    div.partner-comment.d-flex
      .face-icon
        = link_to image_tag(chat.user.avatar, class: 'mr-3 rounded-circle', size: '50x50'), user_path(chat.user)
      .chatting
        .media-body.says
          = simple_format(chat.body)
    div.time
      = chat.decorate.created_at

app/views/chats/_form.html.slim
// Rails6.1から非同期通信は、local: false
= form_with model: [chatroom, chat], class: 'd-inline-flex', local: false do |f|
  = render 'shared/error_messages', object: chat
  .form-group.form-floating
    = f.text_field :body, id: 'fl-text', placeholder: "メッセージ", class: 'form-control input-chat-body', required: ""
    = f.label :body, for: 'fl-text'
  - if chat.new_record?
    = f.submit '送信', class: 'btn btn-primary btn-raised'
  - else
    = f.submit '更新', class: 'btn btn-primary btn-raised'

app/views/chats/_modal_form.html.slim
.modal#chat-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title メッセージ編集
        button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
      .modal-body.modal-edit
        = render 'form', chatroom: nil, chat: @chat

app/views/chats/_modal_index.html.slim
.modal#reservation-index-modal
  .modal-dialog.modal-md
    .modal-content
      .modal-header
        h5.modal-title
          = "#{current_user.partner(@chatroom).username}さんとの予約"
        button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
      .modal-body
        = render 'reservations/reservation_list_chatroom'

app/views/chats/destroyl.js.slim
| $('#chat-#{@chat.id}').remove()

app/views/chats/edit.js.slim
| $("#modal-container").html("#{escape_javascript(render 'modal_form', chat: @chat)}");
| $("#chat-edit-modal").modal('show');

app/views/chats/index.js.slim
| $("#modal-container").html("#{escape_javascript(render 'modal_index', reservation: @reservation)}");
| $("#reservation-index-modal").modal('show');