config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Deviseのマッピングはするが、skipして何も設定しない
  devise_for :users, skip: %i[sessions registrations],
                     controllers: {
                       confirmations: 'users/confirmations',
                       omniauth_callbacks: 'users/omniauth_callbacks',
                       passwords: 'users/passwords'
                     }
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    post 'guest_login', to: 'users/sessions#guest_login', as: :guest_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'users/registrations#new', as: :new_user_registration
    post 'signup', to: 'users/registrations#create', as: :user_registration
    get 'account/edit', to: 'users/registrations#edit', as: :edit_account
    put 'account', to: 'users/registrations#update', as: :account
    delete 'account', to: 'users/registrations#destroy', as: :destroy_account
  end
  root 'static_pages#top'
  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :feedbacks, only: %i[new create]
  resources :crops do
    collection do
      get :search
    end
  end
  resources :users, only: %i[show]
  namespace :mypage do
    get 'following', to: 'relationships#following'
    get 'follower', to: 'relationships#follower'
    resources :notifications, only: %i[index]
  end
  resources :reservations, only: %i[index new create destroy]
  resources :bookmarks, only: %i[index create destroy]
  resources :relationships, only: %i[create destroy]
  resources :chatrooms, only: %i[index create show], shallow: true do
    resources :chats
  end
  resources :notifications, only: [] do
    patch :read, on: :member
    patch :read_all, on: :collection
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/crop.rb
# == Schema Information
#
# Table name: crops
#
#  id           :bigint           not null, primary key
#  description  :text(65535)
#  harvested_on :date
#  name         :string(255)      not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_crops_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Crop < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :name, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 1000 }
  validates :harvested_on, presence: true
  has_one_attached :picture
  validate :picture_presence
  validates :picture,
            content_type: { in: %w[image/jpeg image/gif image/png], message: 'は有効なファイルを選択してください' },
            size: { less_than: 5.megabytes, message: 'は5MB以下を選択してください' }
  # 1週間以内に収穫した作物を抽出
  scope :harvested_within_a_week, -> { where('harvested_on >= ?', 1.week.ago.beginning_of_day) }
  scope :sorted, -> { order(harvested_on: :desc) }
  scope :reverse_sorted, -> { order(harvested_on: :asc) }
  # 未予約の作物を抽出
  scope :not_reserved, -> { includes(:reservations).where(reservations: { crop_id: nil }) }
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user
  has_one :notification, as: :subject, dependent: :destroy
  after_create_commit :create_notifications
  acts_as_mappable through: :user
  extend OrderAsSpecified

  def harvested_after_a_week?
    harvested_on < 1.week.ago
  end

  def self.within_distance(object)
    within(5, origin: object.position)
      .includes(:user)
      .harvested_within_a_week
      .not_reserved
  end

  private

  def picture_presence
    errors.add(:picture, 'ファイルを添付してください') unless picture.attached?
  end

  def create_notifications
    user.followers.each do |follower|
      Notification.create(user: follower, subject: self, notification_type: :create_crop_by_follow_user)
    end
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  def index
    if params[:near]
      crops = Crop.within_distance(current_user)
                  .sort_by { |crop| crop.user.distance_to(current_user.position) }
      crop_ids = crops.pluck(:id)
    elsif params[:far]
      crops = Crop.within_distance(current_user)
                  .sort_by { |crop| crop.user.distance_to(current_user.position) }
      crop_ids = crops.pluck(:id).reverse
    elsif params[:new]
      crops = Crop.within_distance(current_user)
                  .sorted
      crop_ids = crops.pluck(:id)
    elsif params[:old]
      crops = Crop.within_distance(current_user)
                  .reverse_sorted
      crop_ids = crops.pluck(:id)
    else
      # 収穫1週間以内、未予約、距離5km以内の作物を取得
      crops = Crop.within_distance(current_user)
                  .sorted
      crop_ids = crops.pluck(:id)
    end
    @crops = Crop.where(id: crop_ids)
                 .order_as_specified(id: crop_ids)
                 .with_attached_picture
                 .includes(user: { avatar_attachment: :blob })
                 .page(params[:page])
                 .per(12)
  end

  def new
    @crop = Crop.new
  end

  def create
    @crop = current_user.crops.build(crop_params)
    if @crop.save
      redirect_to crops_path, success: '作物を登録しました'
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def show
    @crop = Crop.find(params[:id])
  end

  def edit
    @crop = current_user.crops.find(params[:id])
  end

  def update
    @crop = current_user.crops.find(params[:id])
    if @crop.update(crop_params)
      redirect_to crops_path, success: '作物を更新しました'
    else
      flash.now[:danger] = '作物の更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @crop = current_user.crops.find(params[:id])
    @crop.destroy!
    redirect_to crops_path, success: '作物を削除しました'
  end

  def search
    @crops = @q.result(distinct: true)
               .within(5, origin: current_user.position)
               .with_attached_picture
               .includes(user: { avatar_attachment: :blob })
               .harvested_within_a_week
               .not_reserved
               .page(params[:page])
               .per(12)
  end

  private

  def crop_params
    params.require(:crop).permit(:name, :description, :harvested_on, :picture)
  end
end

app/views/crops/_bookmark.html.slim
= link_to bookmarks_path(crop_id: crop.id), method: :post, remote: true do
  i.fa-regular.fa-bookmark.fa-lg class="bookmark"

app/views/crops/_bookmark_area.html.slim
div id="bookmark_area-#{crop.id}"
  - if current_user.bookmark?(crop)
    = render 'crops/unbookmark', crop: crop
  - else
    = render 'crops/bookmark', crop: crop

app/views/crops/_bookmark_crop.html.slim
.col-lg-4.col-sm-6.mb-grid-gutter
  .card.border-0.shadow.product-card.card-static id="crop-#{bookmark_crop.id}"
    - if current_user && !current_user.own?(bookmark_crop)
      button.btn-wishlist.btn-sm data-bs-placement="left" data-bs-toggle="tooltip" type="button"
        = render 'crops/bookmark_area', crop: bookmark_crop
    = link_to crop_path(bookmark_crop) do
      = image_tag bookmark_crop.picture, class: 'crop-detail'
    .card-body.text-center
      = link_to bookmark_crop.name, crop_path(bookmark_crop)
      p.fs-sm.text-muted.pb-2.crop-index
        = bookmark_crop.description
      .fs-xs.text-nowrap.text-start
        a.blog-entry-meta-link.text-nowrap
          | 収穫日
        span.blog-entry-meta-divider.mx-2
        a.blog-entry-meta-link.text-nowrap
          = bookmark_crop.harvested_on
      .fs-xs.text-nowrap.text-start
        a.blog-entry-meta-link.text-nowrap
          | 生産者
        span.blog-entry-meta-divider.mx-2
        a.blog-entry-meta-link.text-nowrap
          = image_tag bookmark_crop.user.avatar, class: 'rounded-circle me-1 user-index'
          = link_to bookmark_crop.user.username, user_path(bookmark_crop.user)
      - if bookmark_crop.reservations.empty?
        = link_to '予約する', new_reservation_path(crop_id: bookmark_crop.id), remote: true, class: 'btn btn-outline-primary btn-sm my-2 reserve-button'
      - else bookmark_crop.harvested_after_a_week? || bookmark_crop.reservations.present?

app/views/crops/_crop.html.slim
.col-lg-4.col-sm-6.mb-grid-gutter
  .card.border-0.shadow.product-card.card-static id="crop-#{crop.id}"
    - if current_user && !current_user.own?(crop)
      button.btn-wishlist.btn-sm data-bs-placement="left" data-bs-toggle="tooltip" type="button"
        = render 'bookmark_area', crop: crop
    = link_to crop_path(crop) do
      = image_tag crop.picture, class: 'crop-detail'
    .card-body.text-center
      = link_to crop.name, crop_path(crop)
      p.fs-sm.text-muted.pb-2.crop-index
        = truncate(crop.description, length: 50)
        - if crop.description.length >= 50
          = link_to '続きを読む', crop_path(crop)
      .fs-xs.text-nowrap.text-start
        a.blog-entry-meta-link.text-nowrap
          | 収穫日
        span.blog-entry-meta-divider.mx-2
        a.blog-entry-meta-link.text-nowrap
          = crop.harvested_on
      .fs-xs.text-nowrap.text-start
        a.blog-entry-meta-link.text-nowrap
          | 生産者
        span.blog-entry-meta-divider.mx-2
        a.blog-entry-meta-link.text-nowrap
          = image_tag crop.user.avatar, class: 'rounded-circle me-1 user-index'
          = link_to crop.user.username, user_path(crop.user)
      .fs-xs.text-nowrap.text-start
        a.blog-entry-meta-link.text-nowrap
          | 距　離
        span.blog-entry-meta-divider.mx-2
        a.blog-entry-meta-link.text-nowrap
          = current_user.distance(crop)
          |  km
      - if current_user&.own?(crop)
        = link_to '編集', edit_crop_path(crop), class: 'btn btn-outline-warning btn-sm my-2 me-2 edit-button'
        = link_to '削除', crop_path(crop), class: 'btn btn-outline-info btn-sm my-2 delete-button', method: :delete, data: { confirm: '本当に削除しますか?' }
      - else
        = link_to '予約する', new_reservation_path(crop_id: crop.id), remote: true, class: 'btn btn-outline-primary btn-sm my-2 reserve-button'

app/views/crops/_form.html.slim
.fs-base.pb-2
  = form_with model: crop, local: true do |f|
    = render 'shared/error_messages', object: crop
    .form-group.mb-3
      = f.label :picture, class: 'ms-3'
      = f.file_field :picture, class: 'form-control'
      - if crop.picture.attached?
        = image_tag crop.picture, class: 'crop-detail ms-4 my-2'
    .form-group.mb-3.form-floating
      = f.text_field :name, id: 'fl-text', placeholder: "作物名", class: 'form-control', required: ""
      = f.label :name, for: 'fl-text'
    .form-group.mb-3.form-floating
      = f.text_area :description, id: 'fl-text', placeholder: "説明", class: 'form-control'
      label 説明 (* 任意)
    .form-group.mb-3
      = f.label :harvested_on, class: 'mx-3'
      = f.date_select :harvested_on, {}, {class: 'form-control', style: 'display: inline-block;width: auto;'}
    .text-center.pt-4
      = f.submit class: 'btn btn-primary btn-raised'

app/views/crops/_thumbnail_crop.html.slim
.col-lg-3.col-md-4.col-sm-6.px-2.mb-grid-gutter
  .card.shadow
    = link_to crop_path(thumbnail_crop), class: 'thumbs' do
      = image_tag thumbnail_crop.picture

app/views/crops/_unbookmark.html.slim
= link_to bookmark_path(current_user.bookmarks.find_by(crop_id: crop.id)), method: :delete, remote: true do
  i.fa-solid.fa-bookmark.fa-lg class="bookmark"

app/views/crops/edit.html.slim
- set_meta_tags title: '作物編集ページ'
.page-title-overlap.bg-accent.pt-4.pb-5
  .container.pt-2.pb-3.pt-lg-3.pb-lg-4
    .d-lg-flex.justify-content-between.pb-3
      .order-lg-1.pe-lg-4.text-left.text-lg-start
        h1.h3.text-light.mb-2.ms-5 作物編集
.container.pb-2
  .bg-light.shadow-lg.rounded-3.overflow-hidden.p-2.pb-4
    .row
      .col-md-8.offset-md-2
        .card.border-0.shadow.crop
          .card-body
            = render 'form', crop: @crop

app/views/crops/index.html.slim
- set_meta_tags title: '作物一覧ページ'
.page-title-overlap.bg-accent.pt-4.pb-5
  .container.pt-2.pb-3.pt-lg-3.pb-lg-4
    .d-lg-flex.justify-content-between.pb-3
      .order-lg-1.pe-lg-4.text-left.text-lg-start.d-sm-flex
        h1.h3.text-light.mb-2.ms-5 作物一覧
        .my-sm-0.my-3.text-sm-end.pt-1.ms-4.flex-column
          .d-flex.align-items-center.text-nowrap.fs-sm
            .mb-2.ms-sm-3.me-2
              span.fw-medium.text-light.me-1
                | 並び順
            .mb-2.ps-sm-2.ps-2.border-start.border-light
              span.fw-medium.text-light.me-1
                = link_to '近い', crops_path(near: 'true'), class: "sort-link #{'active' if current_page?('/crops?near=true')}"
            .mb-2.ps-sm-2.ps-2.border-start.border-light
              span.fw-medium.text-light.me-1
                = link_to '遠い', crops_path(far: 'true'), class: "sort-link #{'active' if current_page?('/crops?far=true')}"
            .mb-2.ps-sm-2.ps-2.border-start.border-light
              span.fw-medium.text-light.me-1
                = link_to '新しい', crops_path(new: 'true'), class: "sort-link #{'active' if current_page?('/crops?new=true')}"
            .mb-2.ps-sm-2.ps-2.border-start.border-light
              span.fw-medium.text-light.me-1
                = link_to '古い', crops_path(old: 'true'), class: "sort-link #{'active' if current_page?('/crops?old=true')}"
.container.pb-3
  .bg-light.shadow-lg.rounded-3.overflow-hidden.p-2
    .row
      .col-md-10.offset-md-1
        .row
          - if @crops.present?
            = render @crops
          - else
            .text-center.font-weight-bold
              | 作物がありません
          = paginate @crops, theme: 'bootstrap-5'

app/views/crops/new.html.slim
- set_meta_tags title: '作物登録ページ'
.page-title-overlap.bg-accent.pt-4.pb-5
  .container.pt-2.pb-3.pt-lg-3.pb-lg-4
    .d-lg-flex.justify-content-between.pb-3
      .order-lg-1.pe-lg-4.text-left.text-lg-start
        h1.h3.text-light.mb-2.ms-5 作物登録
.container.pb-2
  .bg-light.shadow-lg.rounded-3.overflow-hidden.p-2.pb-4
    .row
      .col-md-6.offset-md-3
        .card.border-0.shadow
          .card-body
            = render 'form', crop: @crop

app/views/crops/search.html.slim
- set_meta_tags title: '検索ページ'
.page-title-overlap.bg-accent.pt-4.pb-5
  .container.pt-2.pb-3.pt-lg-3.pb-lg-4
    .d-lg-flex.justify-content-between.pb-3
      .order-lg-1.pe-lg-4.text-left.text-lg-start.d-flex
        h1.h3.text-light.mb-2.ms-5
          = "\"#{@search_word}\""
          | の検索結果
        .my-sm-0.my-3.text-sm-end.pt-1.ms-4.flex-column
          .d-flex.align-items-center.text-nowrap.fs-sm.sort
            .mb-2.ms-sm-3.me-2.text-muted
              span.fw-medium.text-light.me-1
                | 並び順
            .mb-2.ps-sm-2.ps-2.border-start.border-light.text-muted
              span.fw-medium.text-light.me-1
                = sort_link(@q, :user_id, "生産者")
            .mb-2.ps-sm-2.ps-2.border-start.border-light.text-muted
              span.fw-medium.text-light.me-1
                = sort_link(@q, :harvested_on, "収穫日")
.container.pb-3
  .bg-light.shadow-lg.rounded-3.overflow-hidden.p-2
    .row
      .col-md-10.offset-md-1
        .row
          - if @crops.present?
            = render @crops
          - else
            .text-center.font-weight-bold
              | 作物がありません
          = paginate @crops, theme: 'bootstrap-5'

app/views/crops/show.html.slim
- set_meta_tags title: '作物詳細ページ', description: @crop.description
.page-title-overlap.bg-accent.pt-4.pb-5
  .container.pt-2.pb-3.pt-lg-3.pb-lg-4
    .d-lg-flex.justify-content-between.pb-3
      .order-lg-1.pe-lg-4.text-left.text-lg-start
        h1.h3.text-light.mb-2.ms-5 作物詳細
.container.pb-2
  .bg-light.shadow-lg.rounded-3.overflow-hidden.p-2.pb-4
    .row
      .col-md-6.offset-md-3
        .card.border-0.shadow.product-card.card-static id="crop-#{@crop.id}"
          - if current_user && !current_user.own?(@crop)
            button.btn-wishlist.btn-lg data-bs-placement="left" data-bs-toggle="tooltip" type="button"
              = render 'bookmark_area', crop: @crop
          = image_tag @crop.picture, class: 'crop-show'
          .card-body.text-center
            = link_to @crop.name, crop_path(@crop)
            p.fs-sm.text-muted.pb-2.crop-index
              = @crop.description
            .fs-sm.text-nowrap.text-start
              a.blog-entry-meta-link.text-nowrap
                | 収穫日
              span.blog-entry-meta-divider.mx-2
              a.blog-entry-meta-link.text-nowrap
                = @crop.harvested_on
            .fs-sm.text-nowrap.text-start
              a.blog-entry-meta-link.text-nowrap
                | 生産者
              span.blog-entry-meta-divider.mx-2
              a.blog-entry-meta-link.text-nowrap
                = image_tag @crop.user.avatar, class: 'rounded-circle me-1 user-show'
                = link_to @crop.user.username, user_path(@crop.user)
            .fs-sm.text-nowrap.text-start
              a.blog-entry-meta-link.text-nowrap
                | 距　離
              span.blog-entry-meta-divider.mx-2
              a.blog-entry-meta-link.text-nowrap
                = current_user.distance(@crop)
                |  km
            - if current_user&.own?(@crop)
              = link_to '編集', edit_crop_path(@crop), class: 'btn btn-outline-warning btn-sm my-2 me-2 edit-button'
              = link_to '削除', crop_path(@crop), class: 'btn btn-outline-info btn-sm my-2 delete-button', method: :delete, data: { confirm: '本当に削除しますか?' }
            - elsif @crop.reservations.empty?
              = link_to '予約する', new_reservation_path(crop_id: @crop.id), remote: true, class: 'btn btn-outline-primary btn-sm my-2 reserve-button'
            - else @crop.harvested_after_a_week? || @crop.reservations.present?